### ISSUE TITLE
Publish Gherkin package with netstandard 1.5 support

### ISSUE THREAD

**Issue by jorgebay** [cucumber/gherkin-dotnet#11]
Since the [csproj files have been migrated to new format](https://github.com/cucumber/gherkin-dotnet/blob/4e9c6aaea05da6022166923538710692c04759f8/Gherkin/Gherkin.csproj#L3-L4) and you've added support for netstandard 1.5, do you mind publishing it to nuget?

**Comment by SabotageAndi** [comment]
Some PRs (#7, #9, #10) needs to be merged and then we can think about a release to NuGet.org.

@aslakhellesoy Any timeframe when this is happening?

**Comment by jorgebay** [comment]
A beta or rc version (without those enhancements) would be enough for me.

**Comment by aslakhellesoy** [comment]
Hi @SabotageAndi please feel free to merge those PRs. If I give you NuGet access, can you make an rc release and also tag this repo with `v4.1.4.rc1`?

I've added you to the gherkin core team!

**Comment by aslakhellesoy** [comment]
I can add you to NuGet if you tell me your NuGet user name @SabotageAndi

**Comment by SabotageAndi** [comment]
I can do the merging of the PRs and  making the release in the next days.
But I am not sure how merging back to the mono repo works. Is there any doc for that?

NuGet username is: AndreasWillich

**Comment by aslakhellesoy** [comment]
Great I'll let you know when I get you set up. I'll take care of the monorepo sync and CHANGELOG update. Sorry, I need to document that process so anyone in core can do it.

**Comment by SabotageAndi** [comment]
@jorgebay Sorry, didn't had yet anytime for it. Too much other work to do.
I will have a look at it on the weekend.

**Comment by SabotageAndi** [comment]
@aslakhellesoy I made some last fixes in the package info and activated strong name signing.
Release Build of the NuGet package can be found here: https://www.dropbox.com/s/xl5w87yym8c79s1/Gherkin.4.1.4-rc1.nupkg?dl=0

Could you upload it on NuGet.org as long as I don't have the permissions for that? Thanks!

**Comment by rafaelromao** [comment]
Has this 4.1.4-cr1 release fixed the NETSTANDARD1_5 || NETCOREAPP1_0 || NETCOREAPP1_1 check? When I use *NET Standard 2*, it defaults to .NET 4.5 and breaks my code looking for NET 4.5 libraries.
It would solve the [issue](https://github.com/cucumber/cucumber/issues/259) I reported.

**Comment by rafaelromao** [comment]
> -#if (NETSTANDARD1_5 || NETCOREAPP1_0 || NETCOREAPP1_1)
 +#if (NETSTANDARD1_5 || NETSTANDARD2_0 || NETCOREAPP1_0 || NETCOREAPP1_1 || NETCOREAPP2_0)

Move the project to *NET Standard 2.0* is indeed not necessary, or recommended, but this change, that was part of the rejected [PR 6](https://github.com/cucumber/gherkin-dotnet/pull/6/commits/d0f4e28c9c3dd0e4bd8f30b4fca520554ed88de4) in *[Gherkin/GherkinDialectProvider.cs](https://github.com/cucumber/gherkin-dotnet/blob/master/Gherkin/GherkinDialectProvider.cs)* and *[Gherkin/GherkinLine.cs](https://github.com/cucumber/gherkin-dotnet/blob/master/Gherkin/GherkinLine.cs)*, would fix my [issue](https://github.com/cucumber/cucumber/issues/259) and allow the parser to be used by NET Standard 2.0 projects.

**Comment by SabotageAndi** [comment]
No idea. Please try it and report back.
From the nuspec the package targets NetStandard 1.5 and .net 4.5.
I would assume,that in case of a NetStandard 2.0 lib, it would take the NetStandard 1.5 assembly.

**Comment by SabotageAndi** [comment]
That are compile time ifs. The code is already baked when you reference the assembly.

**Comment by rafaelromao** [comment]
**I just tested the 4.1.4-rc1 and it works with NET Standards 2.**

I guess https://github.com/cucumber/cucumber/issues/259 can be closed when this version gets published.

Thanks

**Comment by gasparnagy** [comment]
@SabotageAndi I have uploaded your package to nuget.org... (also added you to the owners for next time) Thank you!

**Comment by SabotageAndi** [comment]
@gasparnagy Thanks!

**Comment by jorgebay** [comment]
Thanks @gasparnagy and @SabotageAndi!
