### ISSUE TITLE
Package signing breaks the build

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/gherkin-dotnet#12]
@SabotageAndi looks like 8c5a3ef6a3e4d099cb6aff400a9fb3906d26cbed [broke the build](https://travis-ci.org/cucumber/gherkin-dotnet/builds/281898481)

I only discovered it just now - please keep an eye on CI when you push.

Any idea how to fix this?

**Comment by SabotageAndi** [comment]
Oh, sorry. Didn't notice that gherkin-dotnet is now building also on Travis.
Somewhen in the past it was disabled.

Error is, because it looks like that assembly signing is only supported on Windows.
I will disable it on Linux & MacOS

**Comment by SabotageAndi** [comment]
Fixed
