### ISSUE TITLE
Would you accept a pull request to make this .Net 3.5 compatible?

### ISSUE THREAD

**Issue by Jaykul** [cucumber/gherkin-dotnet#3]
There are just two changes necessary to make it compile against .Net 3.5, and I'd really like to be able to use this in a project that needs to be PowerShell 2 compatible.

**Comment by gasparnagy** [comment]
@Jaykul we do accept pull requests in general, but please note that this repository is just a mirror of the dotnet folder of the https://github.com/cucumber/gherkin repository, so you should submit the PRs there.
Regarding 3.5 compatibility... I'm not sure if it is a good idea to "downgrade" the project. .NET 3.5 is pretty old and if you really need a Gherkin parser for that, you can still use the Gherkin 2 parser (https://www.nuget.org/packages/gherkin/2.12.2). But let's discuss it in the main Gherkin repo. You can also have discussions in the Gitter Gherkin channel: https://gitter.im/cucumber/gherkin
